language: node_js
node_js: 8
sudo: required
before_script: npm install -g polymer-cli @advanced-rest-client/wct-istanbub
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  sauce_connect: true
script:
- xvfb-run polymer test --module-resolution=node --npm --plugin local
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then polymer test --module-resolution=node
  --npm --plugin sauce --job-name "payload-parser-mixin:${TRAVIS_BRANCH}" --build-number=${TRAVIS_BUILD_NUMBER};
  fi
env:
  global:
  - secure: brDTDILhKM9AJ4ZMFvwG/HR7AI3Fn3IFJOjeEf2VEgvAkSvTMvX8SW8EmnyyNbyOONSunCB4n8SExBj1arCfNbnZbaL2qASg2ha2lKdhIuf0/2QlxEAPptrXS6fDCNNZy1Yl8DhxkT+tusUd0rXRyRfWdvJO9dntN/iNyDfWrC6R3Gjezk0rkjaudogOTxB2E3rr5TelGN51LvTUUW/joVuh6Ve603JNbaodRGzJ00jc++YrjeSdlURyochLLcKHX0dqFa8a7dEHoZ5J1CKCtzVQO+axyP0UyjN2z4hELboeZuPTmaF37adtDrfH3wl3S6v8qu1AwInyh3FsRErNPYsb8ylKp7j0nx71T3KLqZZma/CR4ltNlELWg2NYtLArFOMHiDN6W5XBoTVROsBJwA6mX/ogLKpKmD4ntrGkgq1e5s1NUzVPhbiMZZLXwr/Uo90qm/lvd2kUvFs3dPIWzrwfuC6XdRRmaq7YzMYq6q4Kx8WjGxajMZ6jYF2EK73mjzEDvTv8K63WNvWio87mViBpdsjajCULyEr2FsSvJZw4sHWLXQgd7NP386xgNLAnO9xrPo7v8bDpOIfofqZF4t9LmTtoNfuwY+n7T24Z3cctlcAB2jCPSDMJH+Uftom7DEZSjc6XSQBwL8xlv19eZusndikF26tNrjqbgpTdNN4=
  - secure: sBNNx0knMWXEDaRaVtdKEr5B4AGGNoK/mf7vCqiiCnOjUyIlKtWlkiutja2LeS4is7glAi1dwliBGJOL6RLHI9vYpZbp575gUA8+ltTGIXaZXYjJdiUJ+nXZuolQnewDMuU2Zf5vU7EPjYu5Eb/wP6gAiP+/X1rJiuq6jXw2MNW/PghN0BihbLLqimMZcp6f94EMAh6kyTdXGgk8mn98kq2kD0paDXrx1vaxkAsxrl2cHs6kcY/AC7Rgip9aSPY/L9EshjckcN2s8lWca/VGM53ZFwy1n+JiFfX4LCLG5LUInGSMNNzQ1E5sirjf+xCP7IKjLTOFK2GvXQ3/R3ixY47RqgiYJ9HfXT/TCUnIhOkavHn8HroKlsvmOGltke6d58MQT5P2agqRm8b0mUeeXylbCFBcW1XTrTcwtOFVWpSqtAeLMFG34x4oLPQpme667rFA07DuNyhqVdJI2uG5kE3JKgLMW3kyudAePsaO9oWQ2SiCk/vBh2VZ5Ygj3FFCIkuef95Kt0WGXYWdmlkiGi6/LKurJ7Rc9h8vcug/kYidbi4hCePmzQ9EIpHhaYNhW7D3YsyxpxgZMFi8uONEVh+97sxQ1+R216FpPR2NQopYRoira08yj/eCeljcn8qOJWjqXYIaQyDedz5St9qUqfLqtO8rWbeNemHBXC/vet0=
